version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd packages/product
      - npm install
  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  base-directory: out
  files:
    - '**/*'